SDC-16127: Fix kafka-multi NullPointer on null payload
streamsets/datacollector pull request #131
Opened 2020-11-01 18:09 UTC by chapsuk

2020-11-01 18:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamsets/datacollector?pullRequest=131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamsets/datacollector?pullRequest=131) before we can accept your contribution.<br/><hr/>**Maxim Krasilnikov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamsets/datacollector?pullRequest=131) it.</sub>

2020-11-30 10:30 UTC, xbcratos requested changes

2020-11-30 10:30 UTC, xbcratos commented on kafka_multisource-protolib/src/main/java/com/streamsets/pipeline/stage/origin/multikafka/KafkaMultitopicRunnable.java
> +      errorRecordHandler.onError(
Set the correct formatting for this line. It should be (all in a single line as it fits in the length of one line): 
errorRecordHandler.onError(new OnRecordErrorException(record, KafkaErrors.KAFKA_74, messageId));

2020-12-01 18:09 UTC, chapsuk commented on kafka_multisource-protolib/src/main/java/com/streamsets/pipeline/stage/origin/multikafka/KafkaMultitopicRunnable.java
> +      errorRecordHandler.onError(
done

2020-12-09 08:45 UTC, xbcratos commented
After some analysis we have determined null payloads are okay. See: [kafka tombstones](https://medium.com/@damienthomlutz/deleting-records-in-kafka-aka-tombstones-651114655a16)

So we have modified the patch and merged it in master branch. See: https://github.com/streamsets/datacollector/commit/3092137d0db55a4c392b1d138e2595e999ae788c

Hence closing this pull request.

Thanks!

2020-12-09 08:45 UTC, closed without merging

2020-12-10 08:06 UTC, chapsuk commented
Thanks, but keep in mind that single topic consumer [handle null payload as error](https://github.com/streamsets/datacollector/blob/master/kafka_source-protolib/src/main/java/com/streamsets/pipeline/stage/origin/kafka/BaseKafkaSource.java#L284-L295), this difference may be confuse users.